### PR TITLE
Create Kanwal

### PR DESCRIPTION
**Pull request by KanwalBat00l**
Hi, 

I would like to add the following profile picture with my name as asked by supervisors.  Please let me know if I need to update. 

https://github.com/uva-cci/cci-website/content/authors/Kanwal

Kanwal

### CODE REVIEW

**Comment by leegbestand** [comment]
Hi @KanwalBat00l , can you put your submission in the content folder. You currently have it under the exampleSite, which is something that I should remove.

Sorry for the confusion and the late response.

**Comment by leegbestand** [comment]
If you want me to do it, that is perfectly fine.

**Comment by leegbestand** [comment]
I did this for you in 5455be3e9b07cb80440ee7391e6807249b24d129 will now close the issue. Again sorry for the long delay.

**Comment by KanwalBat00l** [comment]
Hi,
I figured out and sent a new request today. I've tried to pull and synch in content/authors/Kanwal folder, which does not allow me to update as I might not have rights to update master branch. I forked a branch and updated there. Maybe you can merge that branch/accept changes.

You may find my already created folder with name Kanwal and updated 2 files at this path. content/authors/Kanwal


Regards,
Kanwal



________________________________

**Comment by leegbestand** [comment]
Hi Kanwal, 

I don't see the new commits or pull request. 

Could you create a new pull request with the changes? Thanks in advance. 

Cheers,
Damian

**Comment by KanwalBat00l** [comment]
Hi Damian, 

I sent a pull request again. Hope it works now. Please let me know if you still cannot see. Thanks

**Comment by leegbestand** [comment]
Hi Kanwal, 

No, I still don't see the pull request. I do see changes on your fork though. 
See [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request#creating-the-pull-request) for more information on creating a pull request 

I can probably also create a patch from your personal fork and apply it on the master branch. Let me know what you prefer.

**Comment by KanwalBat00l** [comment]
Hi Damian,

Thank you for the response. I created a pull request yesterday but it didn't work. I will try later now.

Please create a patch if you are comfortable. Thanks a bunch.

Kind regards,
Kanwal


________________________________

**Pull request closed without merging**
