### PR TITLE
Update Kanwal 

### PR DESCRIPTION
**Pull request by KanwalBat00l**

### CODE REVIEW

**Comment by KanwalBat00l** [comment]
Hi Damian, 

thanks for the update. The changes are not shown in the author profile yet. The following link with the CCI website still shows the older content. https://cci-research.nl/author/kanwal-batool/

**Comment by KanwalBat00l** [comment]
Yep. I also found the posts under Latest category. But I also changed my research focus in "About Kanwal" and it's not updated. I think the following commit is not visible or updated on the web. 

Update cci-website/content/authors/Kanwal/_index.md

**Comment by leegbestand** [comment]
Ah yes, I see now.

**Comment by leegbestand** [comment]
It's because the commit targets cci-website/content/authors/Kanwal/_index.md
but your author folder is with the lower letter k, not K. So it should be cci-website/content/authors/kanwal/_index.md

**Comment by KanwalBat00l** [comment]
I changed and sent the pull request again 😕


________________________________

**Pull request merged**
